routes/web.php
<?php

/**
 * Authentication
 */
Route::get('login', 'Auth\AuthController@getLogin')->name('login');
Route::post('login', 'Auth\AuthController@postLogin')->name('post.login');

Route::get('logout', [
    'as' => 'auth.logout',
    'uses' => 'Auth\AuthController@getLogout'
]);

Route::group(['middleware' => 'auth'], function () {

    /**
     * Dashboard
     */
    Route::get('/', [
        'as' => 'dashboard',
        'uses' => 'DashboardController@index'
    ]);

    /**
     * Profiles Details
     */
    Route::get('/profile', [
        'as' => 'profiles.index',
        'uses' => 'ProfileController@index'
    ]);
    Route::post('/profile/profile', [
        'as' => 'profiles.profile',
        'uses' => 'ProfileController@profileUpdate'
    ]);
    Route::post('/profile/account', [
        'as' => 'profiles.account',
        'uses' => 'ProfileController@accountUpdate'
    ]);
    Route::post('/profile/password', [
        'as' => 'profiles.password',
        'uses' => 'ProfileController@passwordUpdate'
    ]);

    /*
    * Users, Role, and Permissions
    */
    Route::resource('users','UserController');
    Route::resource('roles','RoleController');
    Route::resource('permissions','PermissionsController');

    /* Master Data */
    Route::resource('banjar','BanjarController', [
        'except' => 'show'
    ]);
    Route::get('banjar/dtb-banjar', [
        'as' => 'get.dtb-banjar',
        'uses' => 'BanjarController@getData'
    ]);
    Route::resource('dasawisma','DasawismaController', [
        'except' => 'show'
    ]);
    Route::get('dasawisma/dtb-dasawisma', [
        'as' => 'get.dtb-dasawisma',
        'uses' => 'DasawismaController@getData'
    ]);

    /* Registrasi */
    /* Define views for Laravel and reserved routes for Vue*/
    Route::get('registrasi/{tipe}',[
        'as' => 'registrasi.tipe',
        'uses' => 'RegistrasiController@indexRegistrasi'
    ]);
    Route::get('registrasi/buat-data-baru/{tipe}',[
        'as' => 'create.registrasi.tipe',
        'uses' => 'RegistrasiController@create'
    ]);
    Route::get('poli/{tipe}/{reg_id}', [
        'as' => 'poli.tipe',
        'uses' => 'RegistrasiController@indexPoli'
    ]);
    Route::get('poli/{tipe}/{reg_id}/{id}/ubah-data', [
        'as' => 'registrasi.edit',
        'uses' => 'RegistrasiController@edit'
    ]);

    /* For Laravel and Vue Controller */
    Route::get('data-registrasi/registrasi/{tipe}', [
        'as' => 'index.registrasi',
        'uses' => 'RegistrasiController@getData'
    ]);
    Route::get('data-registrasi/registrasi/dtb-registrasi/{tipe}', [
        'as' => 'get.dtb-registrasi',
        'uses' => 'RegistrasiController@getDataRegistrasi'
    ]);
    Route::get('data-poli/poli/dtb-poli/{tipe}/{reg_id}', [
        'as' => 'get.dtb-poli',
        'uses' => 'RegistrasiController@getDataPoli'
    ]);
    Route::get('data-poli/poli/{tipe}/{reg_id}/{id}', [
        'as' => 'get.data-poli',
        'uses' => 'RegistrasiController@getPrevData'
    ]);
    Route::post('registrasi/store-balita', [
        'as' => 'registrasi.balita.post',
        'uses' => 'RegistrasiController@storeBalita'
    ]);
    Route::post('registrasi/store-ibuhamil', [
        'as' => 'registrasi.ibuhamil.post',
        'uses' => 'RegistrasiController@storeIbuHamil'
    ]);
    Route::post('registrasi/store-wuspus', [
        'as' => 'registrasi.wuspus.post',
        'uses' => 'RegistrasiController@storeWusPus'
    ]);
    Route::post('poli/store-balita', [
        'as' => 'poli.balita.post',
        'uses' => 'RegistrasiController@storePoliBalita'
    ]);
    Route::post('poli/store-ibu-hamil', [
        'as' => 'poli.ibuhamil.post',
        'uses' => 'RegistrasiController@storePoliIbuHamil'
    ]);
    Route::post('poli/store-wus-pus', [
        'as' => 'poli.wuspus.post',
        'uses' => 'RegistrasiController@storePoliWusPus'
    ]);
    Route::delete('registrasi/delete-balita/{reg_id}', [
        'as' => 'registrasi.balita.delete',
        'uses' => 'RegistrasiController@destroyRegistrasiBalita'
    ]);
    Route::delete('registrasi/delete-ibu-hamil/{reg_id}', [
        'as' => 'registrasi.ibuhamil.delete',
        'uses' => 'RegistrasiController@destroyRegistrasiIbuHamil'
    ]);
    Route::delete('registrasi/delete-wus-pus/{reg_id}', [
        'as' => 'registrasi.wuspus.delete',
        'uses' => 'RegistrasiController@destroyRegistrasiWusPus'
    ]);

    /* Laporan */
    Route::get('laporan', [
        'as' => 'laporan.index',
        'uses' => 'LaporanController@index'
    ]);
});

app/Http/Controllers/DasawismaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Requests\MasterData\Dasawisma\CreateRequest;
use App\Http\Requests\MasterData\Dasawisma\UpdateRequest;
use App\MDasawisma;
use App\MBanjar;
use DataTables;

class DasawismaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('auth');
        $this->middleware('permission:master-data-manage');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('master-data.dasawisma.index');
    }

    public function getData()
    {
        $query_data = MDasawisma::join('m_banjar as mb', 'mb.id', '=', 'm_dasawisma.banjar_id')
                        ->select(
                            'm_dasawisma.*',
                            'mb.nama_banjar'
                        )
                        ->get();

        return DataTables::of($query_data)
                ->addIndexColumn()
                ->addColumn('action', function ($query_data) {
                    return '
                        <a class="btn btn-warning btn-sm" data-skin="dark" data-toggle="kt-tooltip" data-placement="top" title="Ubah" data-original-title="Dark skin" href="'.route('dasawisma.edit', $query_data->id).'">
                            <i class="flaticon2-edit"></i>
                        </a>
                        <button type="button" class="btn btn-danger btn-sm" data-skin="dark" data-toggle="kt-tooltip" data-placement="top" title="Hapus" data-original-title="Dark skin" onclick="Delete.data('.$query_data->id.')">
                            <i class="flaticon-delete"></i>
                        </button>
                    ';
                })
                ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $edit = false;
        $banjars = MBanjar::all();

        return view('master-data.dasawisma.add-edit', compact('edit', 'banjars'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $request)
    {
        $input = $request->all();
        MDasawisma::create($input);

        return redirect()->route('dasawisma.index')
        ->withSuccess('Berhasil Membuat Data Baru!');
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit = true;
        $banjars = MBanjar::all();
        $data = MDasawisma::find($id);

        return view('master-data.dasawisma.add-edit', compact('edit', 'data', 'banjars'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        $input = $request->all();
        $data = MDasawisma::find($id);
        $data->update($input);

        return redirect()->route('dasawisma.index')
        ->withSuccess('Berhasil Mengubah Data!');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = MDasawisma::find($id)->delete();
        
        return response()->json($data);
    }
}

resources/views/master-data/dasawisma/add-edit.blade.php
@extends('layouts.app')

@section('page-title')
    {{ $edit ? trans('app.update_dasawisma') : trans('app.create_dasawisma') }}
@endsection

@section('content')
    <div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">
        <!-- begin:: Content Head -->
        <div class="kt-subheader  kt-grid__item" id="kt_subheader">
            <div class="kt-container  kt-container--fluid ">
                <div class="kt-subheader__main">
                    <h3 class="kt-subheader__title">Dasawisma</h3>
                    <span class="kt-subheader__separator kt-subheader__separator--v"></span>
                    <span class="kt-subheader__desc">{{ $edit ? trans('app.update_dasawisma') : trans('app.create_dasawisma') }}</span>
                </div>
            </div>
        </div>
        <!-- end:: Content Head -->
        <!-- begin:: Content -->
        <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
            <div class="row">
                <div class="col-lg-12">
                    <!--begin::Portlet-->
                    <div class="kt-portlet">
                        <div class="kt-portlet__head">
                            <div class="kt-portlet__head-label wrapper-back__button">
                                <div class="col-md-4 back-button mr-3">
                                    <a class="btn btn-primary" href="{{ route('dasawisma.index') }}">
                                        <i class="fa fa-angle-left"></i> 
                                        Kembali
                                    </a>
                                </div>
                            </div>
                        </div>

                        @include('partials.messages')
                        
                        <!--begin::Form-->
                        @if($edit)
                            {!! Form::open(['route' => ['dasawisma.update', $data->id], 'method' => 'PUT', 'class' => 'kt-form kt-form--label-right', 'id' => 'kt_form_1', 'enctype' => 'multipart/form-data']) !!}
                        @else
                            {!! Form::open(['route' => 'dasawisma.store', 'class' => 'kt-form kt-form--label-right', 'id' => 'kt_form_1', 'enctype' => 'multipart/form-data']) !!}
                        @endif
                            <div class="kt-portlet__body">
                                <div class="form-group row">
                                    <label class="col-form-label col-lg-3 col-sm-12">Nama Banjar*</label>
                                    <div class="col-lg-6 col-sm-12">
                                        <select class="form-control kt-select2" name="banjar_id" id="kt_select2_4">
                                            <option value=""></option>
                                            @foreach($banjars as $banjar)
                                                @if(isset($data->banjar_id) && $data->banjar_id == $banjar->id)
                                                    <option value="{{ $banjar->id }}" selected >{{ $banjar->nama_banjar }}</option>
                                                @else
                                                    <option value="{{ $banjar->id }}">{{ $banjar->nama_banjar }}</option>
                                                @endif
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-form-label col-lg-3 col-sm-12">Nama Dasawisma*</label>
                                    <div class="col-lg-6 col-sm-12">
                                        <input type="text" name="nama_dasawisma" class="form-control" placeholder="Masukkan Nama Dasawisma" value="{{ $edit ? $data->nama_dasawisma : old('nama_dasawisma') }}" id="nama_dasawisma">
                                    </div>
                                </div>
                            </div>
                            <div class="kt-portlet__foot">
                                <div class="kt-form__actions kt-form__actions--right">
                                    @if($edit)
                                        {{-- <button type="button" class="btn btn-danger mr-3" id="reset">
                                            <i class="flaticon2-circular-arrow"></i>
                                            Reset
                                        </button> --}}
                                        <button type="submit" class="btn btn-success">
                                            <i class="flaticon2-checkmark"></i>
                                            {{ $edit ? trans('app.update') : trans('app.save') }}
                                        </button>
                                    @else
                                        <button type="submit" class="btn btn-success">
                                            <i class="flaticon2-checkmark"></i>
                                            {{ $edit ? trans('app.update') : trans('app.save') }}
                                        </button>
                                    @endif
                                </div>
                            </div>
                        {!! Form::close() !!}
                        <!--end::Form-->
                    </div>
                    <!--end::Portlet-->
                </div>
            </div>
        </div>
        <!-- end:: Content -->
    </div>
@endsection

resources/views/master-data/dasawisma/index.blade.php
@extends('layouts.app')

@section('page-title')
    Master Data Dasawisma
@endsection

@section('content')
    <div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">
        <!-- begin:: Content Head -->
        <div class="kt-subheader  kt-grid__item" id="kt_subheader">
            <div class="kt-container  kt-container--fluid ">
                <div class="kt-subheader__main">
                    <h3 class="kt-subheader__title">Dasawisma</h3>
                    <span class="kt-subheader__separator kt-subheader__separator--v"></span>
                    <span class="kt-subheader__desc">Master Data Dasawisma</span>
                </div>
            </div>
        </div>
        <!-- end:: Content Head -->
        <!-- begin:: Content -->
        <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
            <div class="row">
                <div class="col-lg-12">

                    @include('partials.messages')
                    
                    <!--begin::Portlet-->
                    <div class="kt-portlet">
                        <div class="kt-portlet__head">
                            <div class="kt-portlet__head-label">
                                <span class="kt-portlet__head-icon">
                                    <i class="flaticon2-layers"></i>
                                </span>
                                <h3 class="kt-portlet__head-title">
                                    Data Dasawisma
                                </h3>
                            </div>
                            <div class="kt-portlet__head-toolbar">
                                <div class="kt-portlet__head-actions">
                                    <a class="btn btn-success" href="{{ route('dasawisma.create') }}"> 
                                        <i class="flaticon2-plus"></i>
                                        Buat Data Baru
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="kt-portlet .kt-portlet--mobile">
                            <div class="kt-portlet__body">
                                <!--begin::Section-->
                                <div class="kt-section">
                                    <div class="kt-section__content">
                                        <div class="table-responsive">
                                            <!--begin: Datatable -->
                                            <table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_1">
                                                <thead>
                                                    <tr>
                                                        <th>No.</th>                                
                                                        <th>Nama Banjar</th>
                                                        <th>Nama Dasawisma</th>
                                                        <th>Aksi</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    
                                                </tbody>
                                            </table>
                                            <!--end: Datatable -->
                                        </div>
                                    </div>
                                </div>
                                <!--end::Section-->
                            </div>
                        </div>
                    </div>
                    <!--end::Portlet-->
                </div>
            </div>
        </div>
        <!-- end:: Content -->
    </div>
@endsection

@section('scripts')
    <script src="{{ url('assets/js/ajax-master-dasawisma.js') }}" type="text/javascript"></script>
@endsection